### ISSUE TITLE
Configuracion para Nagios

### ISSUE THREAD

**Issue by gabrielsoltz** [nuxsmin/sysMonDash#1]
Hola, como estas, quería probar tu dashboard, ya que uso syspass y la verdad lo considero ya una herramienta indispensable. Uso Nagios. Lo configuré como creí que debía hacerlo, pero no logro hacerlo funcionar, necesita alguna configuración especial de apache ? (el unico archivo que toque es config.php). 

Las variables que toque:
$statusFile = '/usr/local/nagios/var/status.dat';
$use_livestatus = true;
$livestatus_socket_path = 'unix:/usr/local/nagios/var/rw/live';
$monitorServerUrl = 'http://miserver.com/nagios';

Me falto algo ?

Gracias!

**Comment by nuxsmin** [comment]
Hola!

Me alegro que te interese la aplicación (además de sysPass) :)

Si corre en Debian tienes que instalar el paquete check-mk-livestatus y configurarlo en Nagios (hay bastantes docs), y posteriormente modificar la ruta al socket unix que crea. Parece complicado, pero no lo es. 

Saludos!

**Comment by gabrielsoltz** [comment]
Es sobre Centos, pero está instalado, de hecho utilizo nagvis mediante mklivestatus. 
Igualmente no funciona.

**Comment by nuxsmin** [comment]
Bien, pues comprueba los permisos del archivo live y su ruta, ya que el usuario del servidor web (creo q httpd) tiene que tener permisos de lectura (imagino que para NagVis lo hiciste). Por otro lado, tienes SELinux activo?

**Comment by gabrielsoltz** [comment]
Ambas cosas chequeadas. No sería ese el problema. Tampoco vi errores en los logs de apache. :/

**Comment by nuxsmin** [comment]
Que error te aparece en el navegador?

**Comment by gabrielsoltz** [comment]
Ninguno. carga la página pefecto, pero no trae ninguna data por debajo del "header".

**Comment by nuxsmin** [comment]
Prueba la URL: /Inc/functions.php?raw=1

Tiene pinta de ser javascript, sabes utilizar firebug (en Firefox)

**Comment by gabrielsoltz** [comment]
Hosts
Array
(
)
Servicios
Array
(
)
Paradas
Array
(
)

**Comment by nuxsmin** [comment]
No es javascript...

Hay algo que impide leer el socket. Yo lo he instalado (ayer mismo) sobre una configuración por defecto de PHP (sin módulos adicionales) y ha funcionado.

Supongo que habrá alertas no?

Prueba también la URL: /ajax/get_monitor_data.php?t=0

**Comment by gabrielsoltz** [comment]
Estado  Desde   Host    Información de Estado  Servicio

No hay avisos para mostrar
20:40:19 @0.008s (auto en 10s)
0 avisos ocultos (Mostrar Todos) 

Pero si hay eventos... Jmmm.. 

Cuando pongo mostrar todos, me lleva a /ajax/index.php?t=1, pero esa pagina no existe (404), eso esta bien?

**Comment by nuxsmin** [comment]
Si es correcto utiliza rutas relativas.

Prueba la URL: /inc/functions.php?raw=1&allheaders=.1

**Comment by gabrielsoltz** [comment]
Hosts
Array
(
)
Servicios
Array
(
)
Paradas
Array
(
)

**Comment by nuxsmin** [comment]
Sabes la versión de livestatus?

**Comment by nuxsmin** [comment]
Prueba:

echo -e "GET hosts\nOutputFormat:json\n\n" | unixcat /var/lib/nagios/rw/live

**Comment by gabrielsoltz** [comment]
La versión es 1.2.6p4
El comando que me indicas trae muchisima data.

Por ej:

[1,0,0,"/pnp4nagios/index.php/graph?host=$HOSTNAME$&srv=_HOST_' class='tips' rel='/pnp4nagios/index.php/popup?host=$HOSTNAME$&srv=_HOST_","/pnp4nagios/index.php/graph?host=cuc1.XXX.com.ar&srv=_HOST_' class='tips' rel='/pnp4nagios/index.php/popup?host=cuc1.XXX.com.ar&srv=_HOST_",1,"10.10.0.72","cuc1.XXX.com.ar","check-host-alive","check-host-alive",0,0,5.0000000000e+00,0,"24x7",0,1,[],^C

**Comment by nuxsmin** [comment]
Ok voy a tratar de reproducir el entorno, ya que las versiones difieren (en Debian  1.1.12p7), por lo que puede que hayan cambiado parámetros, aunque los utilizados están disponibles en la documentación actual.

**Comment by nuxsmin** [comment]
Hola, lo he estado probando con CentOS 7 y la versión de mk-livestatus 1.2.6p9 y funciona correctamente. 

He realizado algunos cambios (subidos a Github)  para interceptar algunos errores de conexión al socket UNIX, puedes comprobar si te muestra algún error?

**Comment by gabrielsoltz** [comment]
Instalé el master y configuré el config.php, veo lo mismo. no muestra ningún error. :/

**Comment by nuxsmin** [comment]
Y probando las URLs de acceso directo? A ver si aparece algo en el log de apache.

**Comment by gabrielsoltz** [comment]
Le saqué el "unix:" de la config del socket y lo dejé como:
$livestatus_socket_path = '/usr/local/nagios/var/rw/live';

Ahora cuando hago /inc/functions.php?raw=1, se llena el array de Servicios.

Sin embargo, sigo sin ver nada en la web.

**Comment by gabrielsoltz** [comment]
En el log de apache hay algunos 304 para ciertos css

**Comment by nuxsmin** [comment]
El código 304 significa que el contenido no ha cambiado, esto es normal.

He subido una nueva versión con cambios en la gestión de errores de JSON, ya que parece que el problema puede estar en el parseo de los datos del socket en formato JSON.

Prueba con esta versión y mira el log de Apache por si aparecen errores.

**Comment by gabrielsoltz** [comment]
No veo ningún error y las URL directas funcionan todas. (Todas me traen datos): 

URL: ajax/get_monitor_data.php?t=0

x.x.x.x - - [29/Sep/2015:14:00:21 -0300] "GET /sysMonDash-master/ajax/get_monitor_data.php?t=0 HTTP/1.1" 200 5757 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"

URL: inc/functions.php?raw=1&allheaders=.1

x.x.x.x - - [29/Sep/2015:14:00:13 -0300] "GET /sysMonDash-master/inc/functions.php?raw=1&allheaders=.1 HTTP/1.1" 200 19591 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0"
