### ISSUE TITLE
config.xml  edit

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysMonDash#11]
the dashboard works. 
but if i missed a config setting,  i have to delete the config.xml
and start with  config.php  from scratch ... 

trying to edit the settings  via config.php does not work.  the requested config hash, has never been displayed.  copy paste from  config.xml  does not work either ... 

am i missing something ?

**Comment by nuxsmin** [comment]
Hi there, surely you have got the wrong hash string, there are two hashes, the "config hash" that is intended for check the config file checksum and a "hash" that is the needed to get into the config.

**Comment by osnet** [comment]
mh k,  if started from scratch ,  where is the access hash stored ?

**Comment by nuxsmin** [comment]
In the config.xml file within `<hash>` labels.
It's done so to avoid to store a password, but I think I would give the choice to use a password instead.

**Comment by nuxsmin** [comment]
Did it work?

**Comment by osnet** [comment]
esta bien !  
PW would be nice ...  not all of our staff has access to shell

**Comment by nuxsmin** [comment]
Bien!, It will be added as a new feature in the next release ;)

**Comment by nuxsmin** [comment]
Hi @osnet , this feature has been implemented in the latest commit ;)
