### ISSUE TITLE
implementation of Zabbix API 3.x

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysMonDash#13]
zabbix 3.x   is able to be viewed with  api 2.4.
thats ok so far. 
but the dashboard does not take the  informationlevels of zabbix 
desaster/high/average/high/normal/info   bla bla 

is there a chance to implement this ?

**Comment by osnet** [comment]
as you can see at dash.power-server.at 
there is a "Warning" for  nas  telling me there are updates 
in fact zabbix displays this as information ( blue )

**Comment by nuxsmin** [comment]
Ok, I think this is not a zabbix 3 related issue, you can take a look to the actual category mappings:

<code>switch ($state) {
            case 0:
                return SERVICE_UNKNOWN;
            case 1:
            case 2:
            case 3:
                return SERVICE_WARNING;
            case 4:
            case 5:
                return SERVICE_CRITICAL;
            default:
                return SERVICE_UNKNOWN;
        }
</code>

There is no associated color to show informational events, because it would become a rainbow like display :) and I would think if those kind of events should be shown at the main display.

**Comment by osnet** [comment]
: )  ya i got your point, 
to be clear  i am more or less "missusing" your  app  since  i want to display all my events  from my manages  zabbix servers on one standalone  monitor in our office ...  
aim : we always are informed whats going on  w/o  having  zabbix  opened on pc : ) 
the common zabbix dashboard does not look that good on 46"  : )

but thanks  for the snip  maybe i am going to adopt it on my own ^^ 
fact :  great work til now

**Comment by nuxsmin** [comment]
Fine...any feedback would be appreciated and the project goal is to be a monitoring central point where you can take look in few seconds what's going on your systems health and keep focused on medium/critical or recent events.

This project was born to catch Nagios like events, so there is a few categories like ok, warning, critical, flapping and unknown, but zabbix does implement a few ones more which would be intermediate states.

BTW, let me know if there's any interesting feature that it lacks on.

**Comment by osnet** [comment]
thats right ,  since we monitor  several wsus  servers ( and the respective clients ) we want to know  how much of the m are patched,  are some clients bugging araound etc . 
here it CAN  be possible to view a warning serveral days.  
this lead to different cases  >80% >50% >40% >20%  the smaller the %  the lower the info level ... 

guess this is a individual thing not to be bothered with dozen of  mails from zabbix : ))

**Comment by osnet** [comment]
aah  hey mate, 
your dashboard is listing up  "only"  unack'ed  events ... : ) 
nice one, how to list ack'ed ones ?  just to fool a lil around for testing

**Comment by nuxsmin** [comment]
Jajaja... don't worry...

You can view it by clicking at the link on the bottom right corner (show more events)

**Comment by nuxsmin** [comment]
Show hidden events...that is the secondary display which is intended to use from a PC because it shows too much info (even filtered events)

**Comment by osnet** [comment]
ja right,  i did not see this, bloody contrast ^^ 
i'm almoste done,  just messing up with .css than it'll be fine  for us , at the moment : )

**Comment by nuxsmin** [comment]
Great!...so late too for your eyes ;)

**Comment by osnet** [comment]
if you'd like to add this to a optional setting, or s/th like that,  i'll send the "rework"

**Comment by nuxsmin** [comment]
Sure, let me know how you did it. If you're familiar with git, you can send a pull request. Otherwise you can send it to nuxsmin at cygnux.org

**Comment by nuxsmin** [comment]
Thanks so much...

I've done some code improvements in order to allow per backend states.

Event's colours have been adapted to MDL color scheme.
