### ISSUE TITLE
language support

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysMonDash#14]
please add a possibility to add language files. // en_US is present but the website is still in mmh spanish ?
and / or rewrite the code entirely in  english ^^ 

thanks

**Comment by nuxsmin** [comment]
Hi there,

It's very strange because you can set en_US in the config options. Didn't work?

Language is automatically detected by browser HTML headers , but it can be overridden by config options.

Hope it works

**Comment by osnet** [comment]
hmmm  have alook @ [http://dash.power-server.at](http://dash.power-server.at)
language ,, idioma > english 
config.xml
 <language>en_US</language>

but there is just spanish stuff ... 

chrome, chromium, safari, IE, edge, mozilla
win7 win10  ubuntu fedora centos
just  spanish stuff

**Comment by nuxsmin** [comment]
Please take a look to the latest commit

**Comment by osnet** [comment]
_TOP_

**Comment by nuxsmin** [comment]
Great, thanks for the feedback;)
