### ISSUE TITLE
strange downtime  display ... 

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysMonDash#15]
if adding a 2nd  or more zabbix servers there is a strange  downtime information. 
![image](https://cloud.githubusercontent.com/assets/1938728/15985668/f1981b84-2ff5-11e6-859f-e0944be9408b.png)
i don't know where this comes from. if this would be maintainance infos then there would be  at leat 5 items.  besides, the time is not correct either

**Comment by nuxsmin** [comment]
Right, those are scheduled maintenance items, but actually the backend is not shown. I'll find out why the time is not correctly shown.

Take care that if there are some hosts that have been associated to a maintenance item, they'll be shown on the same row.

Can you take a look to this URL?: http://yourserver/sysmondash/inc/functions.php?raw=1

**Comment by osnet** [comment]
output ==  < pre >  </ pre > 
ergo emtpy ?

**Comment by nuxsmin** [comment]
Hi @osnet, this issue should be fixed in the latest commit
