### ISSUE TITLE
Adding Language

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysMonDash#16]
editing the  en_US.inc file  to  de_DE.inc 
does not work while SMD is already configured.
-> auto load new  language file doesn't work, 

you'll have to edit  config.php around line 83 to add a new language hardcoded
hitting save : the config file is rewritten with - in my case - de_DE,  the frontend remains en_US

mmh 

btw_  typo error  en_US.inc at line 64

> > $LANG['Ruta socket livestatus'] = 'Licestatus socket path';

**Comment by nuxsmin** [comment]
Is the new language file being placed in its own directory? Does it have the right permissions?.

Language files are loaded if they exists and have the right permissions/owner.

I'll fix that typo... thanks for the feedback!

**Comment by osnet** [comment]
same rights and same owner  as en_US.inc 
both root:root 0644 ( nevermind the root thingy )
same directory > /inc/locales/

**Comment by nuxsmin** [comment]
One more question..did you reset browser session cookie?. That is so because config options and language are saved in the session file/memory (on the server side) for a faster access.

**Comment by nuxsmin** [comment]
It would be great to release the German translation within the next release

**Comment by osnet** [comment]
lol 
reload, ctrl + r, tab lcose and reopen even  browser off on does not work. >> chrome
opening it in a browser on a machine that never has opened the page.  it works. its partial German xD 
maybe some cooke session issue ?   i dont know 

I'll  file you the lang file  if the translation  is  good enough to be released ^^

**Comment by nuxsmin** [comment]
Sure, cookies are kept between reload/restart, so you need to delete browser cookies for this page.

Let me know when it's ready...dank!
