### ISSUE TITLE
config edit bug on actual master - as of 16/6/2016

### ISSUE THREAD

**Issue by osnet** [nuxsmin/sysMonDash#17]
"Nivel no disponible"

caused by 

PHP Notice:  Undefined index: level in /var/www/dash/inc/SMD/Html/Html.class.php on line 104, referer: http://dash.power-server.at/config.php

> > `$ConfigBackend = new ConfigBackendZabbix($config['version'], $config['url'], $config['user'], $config['pass'], $config['level']);`

**Comment by osnet** [comment]
uuh oh  fuck  , ehm my fault ^^   nevermid

**Comment by nuxsmin** [comment]
I think that you didn't set any level at the first time...BTW there was a bug, because the first level should be selected when loaded. The translation wasn't done also...

Thanks for the feedback !

**Comment by osnet** [comment]
no prob, 
here is another one: 
klicking on  Check 
`PHP Fatal error:  require(): Failed opening required 'Exts/Zabbix//ZabbixApi.class.php' (include_path='.:/php/includes:/usr/share/php:/usr/share/pear/PEAR') in /var/www/zabbix-dash/inc/SplClassLoader.php on line 178`, 

with all settings made
`PHP Notice:  Undefined index: level in /var/www/zabbix-dash/inc/SMD/Html/Html.class.php on line 104,`

**Comment by nuxsmin** [comment]
Ummm...that is strange, I haven't ever found that error

**Comment by osnet** [comment]
don't torture  your self  with that ...   i guess there are some settings in the system  managed  by puppet  which keeps reverting my settings somewhere  -.- XD

**Comment by nuxsmin** [comment]
Great... puppet stuff :)

**Comment by osnet** [comment]
yeah, not my system. : )  mine works fine ^^
