### ISSUE TITLE
support for hosting on external server

### ISSUE THREAD

**Issue by wagnst** [nuxsmin/sysMonDash#2]
it's mandatory to host this dashboard on an external webserver which is not the same than the check_mk / icinga / .. monitoring host itself

**Comment by nuxsmin** [comment]
I'll try to find out how to accomplish that because it uses an Unix socket to do the queries, so it needs to have local fs access

**Comment by wagnst** [comment]
i found a different dashboard, which is collecting data from same file but parsing it as json and then i am able to collect this json data from other webserver... may be a way to go...

**Comment by nuxsmin** [comment]
Right, mk_livestatus can send back the response in json format, but in that scenario you will need a webservice to retrieve the data queried and listen for requests and the web server to print out the data.

That is more secure, but it's also more exposed to network glitches and would increase the overhead when the number of clients increases.

What security concerns are about the current design? (Ajax -> webserver).
