### ISSUE TITLE
Question about parallel sysMonDash

### ISSUE THREAD

**Issue by fbergamini** [nuxsmin/sysMonDash#27]
Hello!

First of all, thanks for the development of sysMonDash, it has been very useful to me.

So, I would like to have different screens of sysMonDash showing different services, inspite of it's status. I´ve already managed to modify the code to show services with status OK, but I haven´t been able to run multiple instances of sysMonDash with different configuration. 

I´ve changed the Base.php file to save configuration to another .xml on /etc/sysMonDash, but it didn´t work. Could you please help me?

Thanks a lot, Fabio.

**Comment by nuxsmin** [comment]
Hello Fabio!

I'm glad to know you've found sysMonDash (SMD) useful :)

You can deploy SMD on multiple instances, but be aware that if you're connecting through the same web browser, the PHP session cookie, and thus the session data, will be the same for both, so it most likely will throw an error.

I have successfully deployed 2 instances of SMD one week ago 😄

Regards

**Comment by fbergamini** [comment]
That was precisely the problem! It doesn't throw an error, but it kind of gets lost between configurations. If I configure something on Instance 1, Istance 2 will use the same configuration, so it depends on which instance I load first.

Thanks a lot.
