### ISSUE TITLE
blobs not found in browser

### ISSUE THREAD

**Issue by nobless** [nuxsmin/sysMonDash#30]
Failed to load resource: net::ERR_FILE_NOT_FOUND
blob:http://sysmondash.cygnux.org:11080/8abeea66-5615-4f75-86c3-083ecdc3cd39

![image](https://user-images.githubusercontent.com/11432520/41511609-211d008c-7283-11e8-818f-221f1aba315b.png)

**Comment by nuxsmin** [comment]
I really don't know what means this error since such URL isn't pointed anywhere in sysMonDash. I can browse the demo page from several devices and networks.

![441](https://user-images.githubusercontent.com/1775774/41627926-93329fec-7422-11e8-81d5-d6b535a1a5a9.jpg)

**Comment by nobless** [comment]
I can find it in inspect menu:
![image](https://user-images.githubusercontent.com/11432520/41628092-abf17374-742b-11e8-9bf7-5db96cb89bb5.png)

**Comment by nuxsmin** [comment]
Hmm, no issues on mine (neither console nor network):

![442](https://user-images.githubusercontent.com/1775774/41628189-baf6b6b6-7423-11e8-8362-c5797f2f8e33.jpg)
