### ISSUE TITLE
non chrome browser always autoscrolls

### ISSUE THREAD

**Issue by nobless** [nuxsmin/sysMonDash#33]
When using non chrome browser, like edge or safari, dashboard always autoscroll up and down non stop through all events

its ok when changed
`        smd.Config.setScroll(<?php echo $scroll ? 'true' : 'false'; ?>);`

to:
`        smd.Config.setScroll(false);`

what purpose of this function ?

**Comment by nuxsmin** [comment]
This is the right behaviour, since there would have many events displayed that the height of the screen won't let show all of them, so the auto scrolling helps to checkout them.

**Comment by nobless** [comment]
Ok but it scroll to fast in my opinion ? as an example i can't read any of events, it auto scroll all the time without stopping. so have to disable that :)
