### ISSUE TITLE
blank page when you try to install

### ISSUE THREAD

**Issue by juanfernandovillahernandez** [nuxsmin/sysMonDash#4]
Dear Nu' if you put the url HOST/SMD/config.php the page appear blank.
could you please explain me how I can install SMD?
Best regards

**Comment by nuxsmin** [comment]
Hi! Take care about that you need to create a directory in etc called sysMonDash and make its owner to the webserver user.

Another prerequisite is php >=5.4

There where some steps at wiki 

Let me know if it works

**Comment by nuxsmin** [comment]
Solved in latest release.
