### ISSUE TITLE
El hash de configuración no funciona.

### ISSUE THREAD

**Issue by juanfernandovillahernandez** [nuxsmin/sysMonDash#5]
Es bastante frustante.instalar esta aplicación. No me funciona al ingresar y el hash no lo valida y cuando entras a la pagina principal te sale un error 500.
La aplicación tiene alguna forma de habilitar debug?
puede el archivo de configuración ser editado directamente?
puedo hacer bypass a el hash de configuración?
para que sirve la configuración especial y como debiera de llenarse?
En fin.

Te envio mi log:
log apache 192.168.10.40 - - [29/Mar/2016:08:18:15 -0500] "GET /dashboard/ajax/getData.php?t=0&to=10&_=1459257140936 HTTP/1.1" 500 509 "https://my.url.com/dashboard/" "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36"
apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Oct 14 2015 14:20:21
rphp -v
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

**Comment by nuxsmin** [comment]
Hola, el hash de configuración funciona correctamente, puede ser que no sea el correcto, ya que en el archivo aparecen 2, uno para verificación de integridad y otro para acceder a la configuración via web.

El error 500 puede ser debido a problema en la configuración de los backends y los errores son mostrados en el propio registro de eventos de apache.

He instalado la aplicación en varios sistemas (Debian, Ubuntu, Raspbian, etc) y con versiones de PHP desde la 5.2 hasta 5.6 sin ningún problema.

La configuración especial es para aquellos casos en los que se requiere que el servidor esté instalado por separado del cliente.

Toda la documentación está en la wiki (inglés), si tienes alguna duda coméntamela.

**Comment by juanfernandovillahernandez** [comment]
Por favor podrias mejorar un poco el instalador? si requieres algo de ayuda estoy a tu servicio.

**Comment by nuxsmin** [comment]
Hola, podrías indicarme qué mejoras?

La aplicación sólo requiere de copiar los archivos y configurarla.

En la wiki (en inglés) se encuentran todos los detalles de la instalación y opciones de configuración y los errores son registrados en el registro de apache.

Por cierto, la mayoría de errores no se muestran porque la aplicación está pensada para mostrarla en pantallas de monitorización, por lo que si se muestran errores se verían en la misma.

Has conseguido instalarlo?
