### ISSUE TITLE
DOMDocument.class.php - missing dependency

### ISSUE THREAD

**Issue by epleterte** [nuxsmin/sysMonDash#6]
Hey,
I got this on first attempt to open the dashboard:

```
PHP Warning:  require(DOMDocument.class.php): failed to open stream: No such file or directory in /var/www/html/sysMonDash/inc/SplClassLoader.php on line 178
```

I solved this by installing `php-xml` on CentOS (/RHEL). I suggest to add this dependency to the installation instructions :)

**Comment by nuxsmin** [comment]
Right @epleterte 

Thanks for the feedback ;)

**Comment by osnet** [comment]
hm doesnt work for me on Centos 7 
#####
oh god damnit : )))   my bloody fault !! 
i did not edit the includes  in the  php.ini  xDD 

works now  perfektly

**Comment by nuxsmin** [comment]
Great!

**Comment by nuxsmin** [comment]
Done
